#!/usr/bin/env python3
"""Per-volume render — one standalone PDF document per site section.

The reverse trip of a document transformation: where make_pdfs_single.py renders
the whole site as ONE manual, this renders each top-level section as its OWN
document (vol1.pdf .. volN.pdf), the way a classic controlled document set ships
one self-contained volume per subject. Each volume is the proven single-document
render (one concatenated HTML doc, one Chrome print pass) scoped to one section:

  * standalone numbering  -> inside a volume, the section index is section "1",
                             its topic pages are "2".."N", figures restart at 1
  * own front matter      -> volume title page, numbered TOC (topics + their h2s),
                             table of figures — all exact, read back from the
                             invisible "§H:n§" markers in the rendered text layer
  * own page furniture    -> running section name + "page / total" footer,
                             nested PDF outline (topics with h2 children)
  * cross-volume links    -> anything leaving the volume is retargeted at the
                             published site via PDF_SITE_URL (same-volume links
                             stay working intra-PDF anchors)

Purely additive next to make_pdfs.py / make_pdfs_single.py: it imports their
helpers and modifies neither. Per-volume renders are ~10 pages each, so peak
memory is trivial next to the full single render, and a broken page fails one
volume instead of the whole output.

Outputs: pdfs/vol1.pdf .. pdfs/volN.pdf
Env: same as make_pdfs_single.py (PDF_CHROME_CHANNEL, FIT_WIDE_TABLES, PDF_DATE,
PDF_SITE_URL, PDF_NO_GS), plus PDF_VOLUME=N to build a single volume (smoke test).
"""
from __future__ import annotations

import html
import io
import json
import os
import re
import time

from playwright.sync_api import sync_playwright
from pypdf import PdfReader, PdfWriter

import make_pdfs as M
import make_pdfs_single as S


def group_volumes(manifest: list[dict]) -> list[dict]:
    """Split the manifest into volumes: each section-index entry starts one and
    owns every following non-section entry. The cover (url "") belongs to the
    whole-site manual, not to any volume."""
    volumes: list[dict] = []
    for item in manifest:
        if m := re.fullmatch(r"section-(\d+)/", item["url"]):
            volumes.append({"num": int(m.group(1)), "title": item["title"],
                            "pages": [item]})
        elif volumes and item["url"]:
            volumes[-1]["pages"].append(item)
    return volumes


def volume_title_html(head: str, num: int, title: str, n_pages: int,
                      n_figs: int, date_str: str) -> str:
    body = (
        '<div class="page title-page">'
        f'<div class="kicker">Zensical · Documentation · Volume {num}</div>'
        f"<h1>{html.escape(title)}</h1>"
        '<div class="rule"></div>'
        f'<p class="subtitle">Volume {num} of the {html.escape(M.DOC_TITLE)} '
        "document set, rendered as a standalone document.</p>"
        '<img src="assets/diagram.svg" alt="">'
        '<div class="meta">'
        f"{n_pages} pages &nbsp;·&nbsp; {n_figs} figures<br>"
        f"Generated by the <strong>zenscial-sandbox</strong> CI pipeline<br>"
        f"{html.escape(date_str)}"
        "</div></div>"
    )
    return M.front_page(head, body)


def render_volume(pw_page, port: int, base: str, vol: dict, site_url: str,
                  head: str, date_str: str) -> dict:
    """Render one volume start-to-finish and write pdfs/vol<num>.pdf."""
    num, vtitle, pages = vol["num"], vol["title"], vol["pages"]

    fragments: list[str] = []
    records: list[dict] = []       # per doc-page: number, short, headings
    fig_pre: list[tuple[int, str]] = []
    stats = {"mermaid": 0, "math_pages": 0}
    figno = 0

    for j, item in enumerate(pages):
        url, title = item["url"], item["title"]
        is_index = j == 0
        # Standalone numbering: the volume's index page is section "1", each
        # topic page is "2".."N" — a reader of just this volume sees a document
        # that starts at 1, like any self-contained volume.
        basen = "1" if is_index else str(j + 1)

        pw_page.goto(base + url, wait_until="load", timeout=60000)
        if pw_page.query_selector(".arithmatex"):
            stats["math_pages"] += 1
        defs = M.extract_mermaid(url)
        if defs:
            pw_page.wait_for_function("() => window.mermaid", timeout=25000)
            n = pw_page.evaluate(M.MERMAID_JS, defs)
            if isinstance(n, int):
                stats["mermaid"] += n

        pw_page.add_style_tag(content=M.PRINT_CSS)
        pw_page.add_style_tag(content=S.EXTRA_CSS)
        if os.environ.get("FIT_WIDE_TABLES") == "1":
            pw_page.add_style_tag(content=M.FIT_TABLES_CSS)

        headings = pw_page.evaluate(S.NUMBER_AND_MARK_JS,
                                    {"base": basen, "h1Only": is_index})
        for h in headings:  # drop the theme's trailing permalink marker
            h["text"] = h["text"].removesuffix("¶").strip()

        kinds = pw_page.evaluate(M.FIGURE_KINDS_JS)
        labels, di = [], 0
        short = vtitle if is_index else M.strip_section_prefix(title, vtitle)
        for f in kinds:
            figno += 1
            if f["kind"] == "image":
                cap = (f["alt"] or "Illustration").strip()
            else:
                cap = M.mermaid_caption(defs[di] if di < len(defs) else "")
                di += 1
            labels.append(f"Figure {figno}. {cap}")
            fig_pre.append((figno, f"{short} — {cap}"))
        if labels:
            pw_page.evaluate(M.FIGURE_LABEL_JS, labels)

        fragments.append(pw_page.evaluate(S.REWRITE_JS, j))
        records.append({"number": basen, "short": short, "headings": headings})

    # Same-volume links become intra-PDF anchors; anything else leaves the
    # volume (other sections, the cover, the download buttons) and is retargeted
    # at the published site so it doesn't ship as a dead localhost URI.
    url_to_anchor = {f'"{base}{it["url"]}"': f'"#pg-{j}"' for j, it in enumerate(pages)}

    def relink(frag: str) -> str:
        for src_u, dst in url_to_anchor.items():
            frag = frag.replace(src_u, dst)
        if site_url:
            frag = frag.replace(f'href="{base}', f'href="{site_url}')
        return frag

    articles = "".join(f'<article id="pg-{j}" class="pp">{relink(f)}</article>'
                       for j, f in enumerate(fragments))
    leftover = articles.count(f'href="{base}')
    if leftover and not site_url:
        print(f"  WARNING: vol{num}: {leftover} link(s) leave the volume and still "
              "point at the local render server — set PDF_SITE_URL to retarget them")
    doc_head = head + f"<style>{M.PRINT_CSS}{S.EXTRA_CSS}</style>"
    if os.environ.get("FIT_WIDE_TABLES") == "1":
        doc_head += f"<style>{M.FIT_TABLES_CSS}</style>"
    mj_config = (M.SITE / "javascripts" / "mathjax.js").read_text()
    mathjax = (f"<script>{mj_config}</script>"
               '<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>')
    body_doc = ('<!doctype html><html lang="en"><head><meta charset="utf-8">'
                f'{doc_head}</head><body class="md-typeset">{articles}{mathjax}</body></html>')

    tmp = M.SITE / "__vol_body.html"
    tmp.write_text(body_doc)
    try:
        pw_page.goto(base + "__vol_body.html", wait_until="load", timeout=180000)
        pw_page.wait_for_function("() => window.MathJax", timeout=30000)
        pw_page.evaluate(M.MATHJAX_JS)
        pw_page.wait_for_timeout(300)
        body_bytes = pw_page.pdf(format="A4", print_background=True, margin=S.A4_MARGIN)
    finally:
        tmp.unlink(missing_ok=True)

    # Exact page numbers from the rendered text layer, as in the single render.
    body_reader = PdfReader(io.BytesIO(body_bytes))
    page_texts = [(pg.extract_text() or "") for pg in body_reader.pages]
    total = len(page_texts)
    misses: list[str] = []

    def find_page(token: str) -> int:
        for n, txt in enumerate(page_texts):
            if token in txt:
                return n + 1
        misses.append(token)
        return 1

    head_page = {h["number"]: find_page(f"§H:{h['number']}§")
                 for r in records for h in r["headings"]}
    toc_entries: list[tuple[str, str, str, int]] = []
    for r in records:
        toc_entries.append(("section", r["number"], r["short"],
                            head_page.get(r["number"], 1)))
        for h in r["headings"]:
            if h["tag"] == "h2":
                toc_entries.append(("page", h["number"], h["text"],
                                    head_page.get(h["number"], 1)))
    fig_entries = [(n, cap, find_page(f"Figure {n}.")) for (n, cap) in fig_pre]
    if misses:
        print(f"  WARNING: vol{num}: {len(misses)} marker(s) not found in the "
              f"rendered text layer (entries default to page 1): {misses[:8]}")

    # Front matter through the same themed pipeline.
    title_pdf = M.render_html_to_pdf(
        pw_page, port, "__vtitle.html",
        volume_title_html(head, num, vtitle, len(records), figno, date_str))
    toc_pdf = M.render_html_to_pdf(pw_page, port, "__vtoc.html",
                                   M.contents_html(head, toc_entries))
    tof_pdf = M.render_html_to_pdf(pw_page, port, "__vtof.html",
                                   M.figures_html(head, fig_entries))

    # Assemble: title + contents + figures + body, with per-volume furniture.
    writer = PdfWriter()

    def add(reader: PdfReader) -> int:
        start = len(writer.pages)
        for pg in reader.pages:
            writer.add_page(pg)
        return start

    title_at = add(title_pdf)
    toc_at = add(toc_pdf)
    tof_at = add(tof_pdf)
    body_at = add(body_reader)

    # Running header: the current top-level section of THIS volume.
    starts = sorted((head_page.get(r["number"], 1), f'{r["number"]} {r["short"]}')
                    for r in records)
    chapters = [""] * total
    for k, (sp, ch) in enumerate(starts):
        end = (starts[k + 1][0] - 1) if k + 1 < len(starts) else total
        for s in range(sp, end + 1):
            if 1 <= s <= total:
                chapters[s - 1] = ch
    size = (float(writer.pages[body_at].mediabox.width),
            float(writer.pages[body_at].mediabox.height))
    overlay = M.page_furniture_overlay(chapters, size)
    for k in range(total):
        writer.pages[body_at + k].merge_page(overlay.pages[k])

    # Outline: front matter + numbered topics, each with its h2 children.
    writer.add_outline_item("Title page", title_at)
    writer.add_outline_item("Table of Contents", toc_at)
    writer.add_outline_item("Table of Figures", tof_at)
    for r in records:
        idx = body_at + head_page.get(r["number"], 1) - 1
        parent = writer.add_outline_item(f'{r["number"]} {r["short"]}', idx)
        for h in r["headings"]:
            if h["tag"] == "h2":
                writer.add_outline_item(
                    f'{h["number"]} {h["text"]}',
                    body_at + head_page.get(h["number"], 1) - 1, parent=parent)

    out = M.OUT / f"vol{num}.pdf"
    with open(out, "wb") as f:
        writer.write(f)
    raw, final = S.compress_with_pikepdf(out)
    return {"num": num, "title": vtitle, "pages": len(records), "figures": figno,
            "sheets": len(writer.pages), "body_sheets": total,
            "raw_kb": raw // 1024, "kb": final // 1024,
            "mermaid": stats["mermaid"], "math_pages": stats["math_pages"]}


def main() -> None:
    manifest = json.loads(M.MANIFEST.read_text())
    volumes = group_volumes(manifest)
    only = int(os.environ.get("PDF_VOLUME", "0"))
    if only:
        volumes = [v for v in volumes if v["num"] == only]
        if not volumes:
            raise SystemExit(f"PDF_VOLUME={only}: no such section in the manifest")
    M.OUT.mkdir(parents=True, exist_ok=True)

    httpd = M.start_server()  # chdirs to SITE and serves
    port = httpd.server_address[1]
    base = f"http://127.0.0.1:{port}/"
    t0 = time.time()

    site_url = os.environ.get("PDF_SITE_URL", "").strip()
    if site_url and not site_url.endswith("/"):
        site_url += "/"
    date_str = os.environ.get("PDF_DATE", "").strip() or "Generated in CI"

    channel = os.environ.get("PDF_CHROME_CHANNEL", "chrome").strip().lower()
    launch: dict[str, object] = {"headless": True}
    if channel and channel not in ("chromium", "bundled", "none", ""):
        launch["channel"] = channel

    results: list[dict] = []
    with sync_playwright() as pw:
        browser = pw.chromium.launch(**launch)
        pw_page = browser.new_page(viewport={"width": 1280, "height": 900})
        head = M.theme_head()
        for vol in volumes:
            r = render_volume(pw_page, port, base, vol, site_url, head, date_str)
            results.append(r)
            print(f"  vol{r['num']:<3} {r['title']:<28} {r['pages']} pages  "
                  f"{r['sheets']} sheets  {r['figures']} figures  {r['kb']} KB")
        browser.close()
    httpd.shutdown()

    dt = time.time() - t0
    print("\n=== volume documents assembled ===")
    print(f"time:     {dt:.1f}s for {len(results)} volumes")
    print(f"sheets:   {sum(r['sheets'] for r in results)} total "
          f"({sum(r['body_sheets'] for r in results)} body)")
    print(f"figures:  {sum(r['figures'] for r in results)}   "
          f"mermaid: {sum(r['mermaid'] for r in results)}   "
          f"math pages: {sum(r['math_pages'] for r in results)}")
    print(f"size:     {sum(r['kb'] for r in results)} KB compressed "
          f"(pikepdf, links preserved)")
    print(f"output:   {M.OUT}/vol1.pdf .. vol{max(r['num'] for r in results)}.pdf")


if __name__ == "__main__":
    main()
